executableModuleName=warehouse-app-teavm-wasm
executableModuleVersion=1.0.0-SNAPSHOT
applicationModuleName=warehouse-app
pwa=null
mavenBuildTimestamp=${maven.build.timestamp}
environment=${webfx.meta.environment}